### PR TITLE
Moving legacy functions to own file and setting PHP version check early.

### LINKED ISSUE #28: Parse Error in Curl.php
[31-Aug-2015 12:22:21 UTC] PHP Parse error:  syntax error, unexpected '[' in /srv/bindings/89d174f37673485283ee1f869b9d854d/code/wp-content/plugins/solr-for-wordpress/vendor/solarium/solarium/library/Solarium/Core/Client/Adapter/Curl.php on line 156

```php
if ($endpoint->getOption('ssl')['local_cert']) {
           curl_setopt($handler, CURLOPT_SSLCERT, realpath($endpoint->getOption('ssl')['local_cert']));
       }
```

This site is using PHP 5.3

Case:
#44014
@joshkoenig @erik-pantheon

### LINKED ISSUE #47: syntax error
wp-content/plugins/solr-power/vendor/solarium/solarium/library/Solarium/Core/Client/Adapter/Curl.php:156

and i am not able to index products in live environment

### LINKED ISSUE #71: Add warning for PHP < 5.4
Don't enable, display admin warning, etc.

### PR DESCRIPTION
**Pull request by allan23**
Checks for PHP version right away. If version is less than 5.4 it displays admin notice.
Closes #28. Closes #47. Closes #71.

### CODE REVIEW

**Comment by ataylorme** [comment]
@allan23 I made some updates to your forked branch - please see the [pull request I made there](https://github.com/allan23/solr-for-wordpress-on-pantheon/pull/1).

**Comment by allan23** [comment]
@ataylorme I like this. I'm seeing this working as well. Thanks!

**Comment by ataylorme** [comment]
@allan23 and @joshkoenig  - restarted Travis. Solr download didn't fail this time and everything passed. Any objection to merging this?

**Comment by joshkoenig** [comment]
Seems good to me.

**Pull request merged**
