### PR TITLE
[BUGS-5735] Include schema.xml in release distribution

### PR DESCRIPTION
**Pull request by jspellman814**

### CODE REVIEW

**Review by jazzsequence — APPROVED** [review]
LGTM, any idea why the Behat tests are failing at a password prompt? Would using GH Actions be any improvement?

**Comment by jspellman814** [comment]
@jazzsequence it's failing because of key removal/rotation due to New Relic incident, but I'm working to fix. I'm assuming we'll run into this a lot of the next month or so 😅

**Comment by jazzsequence** [comment]
@jspellman814 I wasn't sure if it was tied to that. If that's the case I'm less worried, but I also wonder if we should migrate away from Circle anyway as a rule.

**Comment by jspellman814** [comment]
I'm totally down for that 🚀 We have a ticket to track that work (1131) that'd I could get started on (would work on that implementation in a separate PR, though).

**Pull request merged**
