### PR TITLE
Admin UI Updates

### PR DESCRIPTION
**Pull request by allan23**
Addresses #163.

### CODE REVIEW

**Comment by ataylorme** [comment]
@allan23 this will need visual review. Can you pull the latest from `master` into this branch and then put it up on a multidev?

**Comment by ataylorme** [comment]
> this will need visual review. Can you pull the latest from master into this branch and then put it up on a multidev?

Nevermind, this is on the main repo and not your fork. I'll take care of this @allan23.

**Comment by ataylorme** [comment]
Screenshot of these updates below:
screen shot 2017-01-08 at 2 11 20 pm

@allan23 let's keep Solr Options as a top level menu item but move indexing options and faceting options back as separate tabs.

Then add icons to the tabs, the yellow header and Pantheon logo as shown in the design on #163.

**Comment by allan23** [comment]
@ataylorme did you grunt before pushing to multidev?

**Comment by ataylorme** [comment]
> did you grunt before pushing to multidev?

I did not - pushing an update now.

**Comment by ataylorme** [comment]
> let's keep Solr Options as a top level menu item but move indexing options and faceting options back as separate tabs. Then add icons to the tabs

@allan23 looking much better. Can you still take are of the above? Then we should be all set.

**Comment by allan23** [comment]
@ataylorme consolidated and icons added.

screen shot 2017-01-09 at 7 21 06 pm

**Pull request merged**
