### PR TITLE
Basic facet widget implementation.

### PR DESCRIPTION
**Pull request by allan23**
Per issue #37, this PR adds a search widget with facet options.

Currently any facet set on the Solr Options page will display. You can also set custom_fields to be facets as well. (As long as they are specified to be indexed and as a facet.)

Filters are also available so that developers can alter the display of available facets.

### CODE REVIEW

**Comment by pantheon-circleci** [comment]
@allan23, thanks for your PR! By analyzing the blame information on this pull request, we identified @joshkoenig, @yvickers and @ataylorme to be potential reviewers

**Comment by ataylorme** [comment]
@allan23 This is totally on the right track and looks really well done.

I'm seeing some unexpected behavior and think we can improve some user experience items.

1) After searching with a facet, such as post type, there is no way to replace the facet with another selection in the search results page (screenshots attached).

solr-facet-initial-search

solr-facet-after-search

When a facet is selected the other available selections need to show up along with the results so a user can change between available items.

2) Let's add a reset button to each facet applied as well as a button to remove all facets from the search.

3) Facets don't show up until after an initial search is performed. An end user might not know they can perform an advanced search if they don't try the simple search first. What do you think of creating an "advanced" accordion/drop down listing all facets?

**Comment by allan23** [comment]
@ataylorme Default facets are available first thing, reset links added below facet items, and filters to add custom fields to index and facets.

**Comment by ataylorme** [comment]
> Default facets are available first thing, reset links added below facet items, and filters to add custom fields to index and facets.

@allan23 this is looking really nice - good work! The last comment I have is that when the text of a search changes and a user hits "Search" again the facets should be reset.

**Comment by ataylorme** [comment]
@allan23 Can you please rebase the master branch of the main repo with your branch for this PR?

**Comment by ataylorme** [comment]
@allan23 can you make this a branch of the Solr Power repo instead of your fork `allan23:issue/37`? The Terminus machine token environment variable in CircleCI isn't passed to forks causing the build to fail.

**Comment by allan23** [comment]
@ataylorme do you want me to do this moving forward or just for this issue? 
I can see how this could be problematic for community contributions.

**Comment by ataylorme** [comment]
@allan23 as we discussed on our call today there seems to be a bug when multiple facets are selected, and shows in the URL, only a single facet is displayed in the widget and search results.

**Comment by allan23** [comment]
@ataylorme This last build is intentionally set to fail. It includes a unit test outlining the issue.
You can select two facets of the same type (two tags for example), but when you try to select two of different types (one tag and one category) no results are found.  
The unit test uses a custom field and a category.

**Comment by ataylorme** [comment]
@allan23 I haven't used Solarium before so I'll dig into this more but could we make use of it's [Facet multiquery feature](http://solarium.readthedocs.io/en/stable/queries/select-query/building-a-select-query/components/facetset-component/facet-multiquery/)?

**Comment by allan23** [comment]
@ataylorme That's the next step I was going to take (in fact I have that documentation bookmarked).

**Comment by ataylorme** [comment]
@allan23 [This article](http://yonik.com/multi-select-faceting/) is pretty interesting. Solr supports the idea of `excludeTags` which allow you to get counts and other info on tags without including them in results. I need to dive deeper to see if Solarium supports this. In the meantime Facet multiquery looks like a good place to start.

**Comment by ataylorme** [comment]
@allan23 [this article](https://enrise.com/2012/11/multi-select-faceting-in-solr-with-solarium/#gist4027542) is good as well. It shows an example of using Solarium's `addFilterQuery` with outer tags.

If I get some time today and tomorrow I'll play around with it. I think this is what we want. Currently `includes/solrpower-api.php` is using `setMinCount` which filters out all elements with zero results. Using `addFilterQuery` with `'tag'=>'outer'` should allow us to return counts for unselected facets without including them in the results.

What do you think?

**Comment by allan23** [comment]
@ataylorme I was looking at the wrong place. It turns out the Filter Query needed an operator. I'll create a new branch so that circleci can run some tests.

**Comment by ataylorme** [comment]
@allan23 closing this in favor of #118, which is a cleaner PR and is where development is happening.

**Pull request closed without merging**
