### PR TITLE
Match author name in search results

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #248

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@ataylorme Do you think it makes sense to include as default behavior, or is it something we should just have documented?

**Comment by ataylorme** [comment]
@danielbachhuber I think it makes sense to match WordPress default behaviour. I'm fine with adding this since `post_title` and `post_content` are still boosted. For example, if I had a post titles `Andrew Jackson` it would return in the results above an author match for `Andrew`

**Comment by danielbachhuber** [comment]
> I think it makes sense to match WordPress default behavior. I'm fine with adding this since `post_title` and `post_content` are still boosted.

WordPress' default behavior is that author name isn't used to produce search results. These two sentences are contradicting statements...

**Comment by ataylorme** [comment]
Sorry, I was reading the issue description in #248.

Documentation is fine. Something like "To have Solr Power match the search term to additional fields besides `post_title` and `post_content` add them to the schema. Example:"

**Comment by danielbachhuber** [comment]
> Documentation is fine. Something like "To have Solr Power match the search term to additional fields besides post_title and post_content add them to the schema.

Sounds good, updated.

**Pull request merged**
