### PR TITLE
Feature/wordpress coding standards

### PR DESCRIPTION
**Pull request by ChrisWiegman**
This pull request addresses #85 

In lieu of adding to CI I propose we do two things:
1. Clean up the extraordinary amount of errors to avoid false positives due to so many existing errors being present.
2. Utilize @stevegrunwell's WP_Enforcer library (https://github.com/stevegrunwell/wp-enforcer). This moves the linting from CI to commit and will simply prevent a dev from committing code not up to standards thereby providing earlier feedback to the dev and preventing CI from throwing a failure for a syntax or similar error.

### CODE REVIEW

**Comment by ataylorme** [comment]
@ChrisWiegman 

> 1) Clean up the extraordinary amount of errors to avoid false positives due to so many existing errors being present.

Yes, the existing errors will need to be cleaned up.

> 2) Utilize @stevegrunwell's WP_Enforcer library (https://github.com/stevegrunwell/wp-enforcer). This moves the linting from CI to commit and will simply prevent a dev from committing code not up to standards thereby providing earlier feedback to the dev and preventing CI from throwing a failure for a syntax or similar error.

This makes sense to me. After We clean up all existing code formatting issues disallowing new issues to be committed will prevent the codebase from having this many code standard issues in the future.

We'll continue down this path but this issue is low priority and should only be attended to after other, higher priority issues are complete.

**Comment by danielbachhuber** [comment]
> In lieu of adding to CI I propose we do two things:

Is there any harm in running PHP Codesniffer on CI in addition to the pre-commit hook?

**Comment by stevector** [comment]
I'v never used it but PHPCS has the ability to auto fix violations: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically

**Comment by jcage88** [comment]
Thanks for the thread here! I am creating my Wordpress website, and it will surely be very helpful for me. It is very cool indeed

**Comment by allan23** [comment]
@ataylorme: this commit consists of cleaned up code that adheres to WordPress Coding Standards, phpcs for grunt (runs on TravisCI), WP Enforcer (phpcs pre-commit hook), and the addition of a bulk sync/indexing option that has sped up unit tests by 61% (instead of relying on the post_status change which adds additional time when there are more than one posts being created).

**Comment by danielbachhuber** [comment]
Restarting this in #251

**Pull request closed without merging**
