### PR TITLE
Flesh out the Composer.json with more details

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by pantheon-circleci** [comment]
@danielbachhuber, thanks for your PR! By analyzing the blame information on this pull request, we identified @calevans to be a potential reviewer

**Comment by ataylorme** [comment]
@danielbachhuber This looks good to me but let's add [the support field](https://getcomposer.org/doc/04-schema.md#support) as well. Since the PR is from your fork I can't edit. If you want to share access I can update.

**Comment by danielbachhuber** [comment]
> This looks good to me but let's add the support field as well.

Updated!

**Comment by ataylorme** [comment]
Thanks @danielbachhuber, looks good. Once we have the Wiki more fleshed out we can add it as a link in the docs field. I'm going to look into why the CicleCI build failed before merging.

**Comment by danielbachhuber** [comment]
> I'm going to look into why the CicleCI build failed before merging.

It failed because it's not configured to run any tests yet, see #95

Fine to merge at this point.

**Comment by ataylorme** [comment]
Gotcha - merging now so we don't block #95.

**Pull request merged**
