### PR TITLE
[CMSP-486] Add is_solr_query filter

### PR DESCRIPTION
**Pull request by sboisvert**
Right now it's impossible to turn off Solr for specific types of searches. 

Another considered solution was to allow for $query->get( 'solr_integrate' ); to be set to false and have that overwrite the result of $query->is_search() but the filter seems like it would give more flexibility and be clearer in it's goal.

### CODE REVIEW

**Comment by rwagner00** [comment]
I created a ticket to look at this internally, thank you for the PR!

**Comment by jazzsequence** [comment]
I love this. @rwagner00 can you update this with the Jira # and/or update the title.

**Comment by rwagner00** [comment]
@jazzsequence  The ticket is: CMSP-486

**Comment by PatelUtkarsh** [comment]
I'd also love to have some control using this filter to exclude specific rest api requests.

**Review by jazzsequence — APPROVED** [review]

**Review by pwtyler — APPROVED** [review]
Not sure why Polyfills is unhappy, pushed to #638 and got a green test. I'll followup to address changelog + doc + minor version bump.

**Pull request merged**
