### PR TITLE
Update Composer dependencies to latest

### PR DESCRIPTION
**Pull request by danielbachhuber**
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 15 updates, 2 removals
  - Removing symfony/debug (v3.4.12)
  - Removing psr/log (1.0.2)
  - Updating symfony/polyfill-ctype (v1.8.0 => v1.9.0): Loading from cache
  - Updating symfony/yaml (v3.4.12 => v4.1.4): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.8.0 => v1.9.0): Loading from cache
  - Updating symfony/translation (v3.4.12 => v4.1.4): Loading from cache
  - Updating symfony/event-dispatcher (v3.4.12 => v3.4.15):  Checking out b2e1f19280
  - Updating symfony/dependency-injection (v3.4.12 => v4.1.4): Loading from cache
  - Updating symfony/console (v3.4.12 => v4.1.4): Loading from cache
  - Updating symfony/filesystem (v3.4.12 => v4.1.4): Loading from cache
  - Updating symfony/config (v3.4.12 => v4.1.4): Loading from cache
  - Updating symfony/class-loader (v3.4.12 => v3.4.15): Loading from cache
  - Updating behat/behat (v3.4.3 => v3.5.0): Loading from cache
  - Updating symfony/dom-crawler (v3.4.12 => v4.1.4): Loading from cache
  - Updating symfony/css-selector (v3.4.12 => v3.4.15): Loading from cache
  - Updating symfony/browser-kit (v3.4.12 => v4.1.4): Loading from cache
  - Updating fabpot/goutte (v3.2.2 => v3.2.3): Loading from cache
Writing lock file
Generating autoload files
```

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@ataylorme Are you fine updating the tested versions to PHP 7.1?

**Comment by ataylorme** [comment]
@danielbachhuber I am okay with this as [the default PHP version for WordPress sites on Pantheon is `7.2`](https://github.com/pantheon-systems/WordPress/blob/default/pantheon.upstream.yml#L6).

That being said if the Symfony dependencies require PHP `7.1` and we are dropping older PHP support then we should make a new release for `2.x` and document PHP `7.1` as a requirement for the `2.x` version

**Comment by danielbachhuber** [comment]
> That being said if the Symfony dependencies require PHP `7.1` and we are dropping older PHP support then we should make a new release for `2.x` and document `PHP 7.1` as a requirement for the `2.x` version

Works for me. Do you want to take care of this and release?

**Comment by ataylorme** [comment]
I can take care of cutting the release but I don't have bandwidth until Friday or next week at the earliest. Anything else you want to get into a release?

I would also like to get a +1 from @joshkoenig on dropping support for PHP < `7.1` and doing a major release.

**Comment by danielbachhuber** [comment]
> I can take care of cutting the release but I don't have bandwidth until Friday or next week at the earliest. Anything else you want to get into a release?

Ok, let's do early next week then. I've assigned myself to #353, #347, #206 and will flag you for review when they're ready.

**Comment by ataylorme** [comment]
Sounds good. I changed the `1.5.1` milestone to `2.0.0` and added those issues to it.

**Comment by danielbachhuber** [comment]
Closing in favor of #379 which includes the Solarium update.

**Pull request closed without merging**
