### PR TITLE
Download and run the Pantheon WordPress Upstream tests

### PR DESCRIPTION
**Pull request by danielbachhuber**
See https://github.com/pantheon-systems/pantheon-wordpress-upstream/issues/6

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@stevector #reviewmerge

**Comment by stevector** [comment]
I will update this PR after https://github.com/pantheon-systems/wp-native-php-sessions/pull/39 is merged.

**Comment by stevector** [comment]
The tests are passing here now @danielbachhuber. Can you review? I'm also assigning to @ataylorme to do the merging.

**Comment by danielbachhuber** [comment]
:shipit:

**Comment by ataylorme** [comment]
@stevector is this still in need of a review/merge?

**Comment by stevector** [comment]
@ataylorme yes

**Comment by ataylorme** [comment]
@stevector I've reviewed the tests and the passing CircleCI results - all looks good here.

**Pull request merged**
