### PR TITLE
Update Solarium to 3.8.1

### LINKED ISSUE #290: Update Solarium to 3.8.1
3.8.1 is the latest release https://github.com/solariumphp/solarium/releases/tag/3.8.1

Is there a reason we're pinned to 3.6.0?

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #290

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> Please update the change log as well

Done.

One thing to note with updating the changelog in each pull request is that we'll have merge conflicts between pull requests if there are multiple pull requests open. It might turn out easier to do them all at the end.

**Comment by ataylorme** [comment]
> One thing to note with updating the changelog in each pull request is that we'll have merge conflicts between pull requests if there are multiple pull requests open. It might turn out easier to do them all at the end.

What about keeping an open PR for change log updates . My goal is to document changes as we go instead of recounting them retroactively and that should solve the problem.

**Comment by danielbachhuber** [comment]
> What about keeping an open PR for change log updates .

Could work.

> My goal is to document changes as we go instead of recounting them retroactively and that should solve the problem.

Why isn't the list of issues assigned to the milestone sufficient for this?

https://github.com/pantheon-systems/solr-power/milestone/9?closed=1

I usually just copy the issue title into the changelog and make minor grammatical tweaks. It doesn't take more than a couple minutes.

**Comment by ataylorme** [comment]
> Why isn't the list of issues assigned to the milestone sufficient for this?

That works as well we just need to be diligent about marking items in milestones, which hasn't happened in the past.

**Pull request merged**
