### PR TITLE
Migrate CircleCI config to v2

### PR DESCRIPTION
**Pull request by danielbachhuber**
Based on https://github.com/pantheon-systems/pantheon-advanced-page-cache/pull/123
See https://github.com/pantheon-systems/pantheon-advanced-page-cache/issues/122

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@ataylorme Looks like `http://solr-power.pantheon.website/wp-content/uploads/apache-solr-3.6.2.tgz` disappeared (domain doesn't resolve). What's the best way to fix?

**Comment by ataylorme** [comment]
@danielbachhuber you can use [https://dev-solr-power.pantheonsite.io/wp-content/uploads/apache-solr-3.6.2.tgz](https://dev-solr-power.pantheonsite.io/wp-content/uploads/apache-solr-3.6.2.tgz)

**Comment by danielbachhuber** [comment]
> Please use the pantheon-public/build-tools-ci Docker image as it has Terminus pre-installed.

Does it have the other dependencies we need? Which PHP version is it?

**Comment by ataylorme** [comment]
It is PHP 7.1 with all of our Terminus plugins and Composer. Not sure what else you need. You can see the Dockerfile [here](https://github.com/pantheon-systems/docker-build-tools-ci/blob/master/Dockerfile)

**Comment by danielbachhuber** [comment]
Ok. WP SAML Auth requires PHP 5.6. I'd prefer to keep the `circle.yml` files consistent between plugin repos and don't see the benefit in using `pantheon-public/build-tools-ci` Docker image.

**Comment by ataylorme** [comment]
The benefit is faster build since the Docker image has Terminus and it doesn't need to be installed on each CircleCI build.

**Comment by danielbachhuber** [comment]
> The benefit is faster build since the Docker image has Terminus and it doesn't need to be installed on each CircleCI build.

Given the Composer checkout is cached, what percentage of total build time does installing Terminus take?

**Comment by ataylorme** [comment]
The [last build](https://circleci.com/gh/pantheon-systems/solr-power/1189) took 4 minutes, which seems okay.

Moving the setup to its own file would still be nice but not necessary.

**Comment by danielbachhuber** [comment]
👍 Thanks @ataylorme

**Pull request merged**
