### PR TITLE
Solarium cleanup

### LINKED ISSUE #14: Update Solarium to 3.5.1
We should get up to 3.3.0. However this is not a priority for the first (alpha) release.

### LINKED ISSUE #72: De-fork Solarium
Pre-requisite for #14 - we have a little shim in Solarium. We should subclass instead like the proper OOPers that we are.

### PR DESCRIPTION
**Pull request by ataylorme**
Defork Solarium (closes #72) by creating the `PantheonCurl` class and update Solarium to 3.6.0 (closes #14).

### CODE REVIEW

**Comment by ataylorme** [comment]
Looks like `symfony/dependency-injection` in Composer requires `symfony/polyfill-mbstring` but installs as a submodule and doesn't pull the files. I had to manually pull the submodule and delete the `.git` directory in `vendor/symfony/polyfill-mbstring`

**Comment by ataylorme** [comment]
Circle CI is failing since the Terminus machine token environment variable isn't passed in PRs

**Comment by danielbachhuber** [comment]
> Circle CI is failing since the Terminus machine token environment variable isn't passed in PRs

You should close this PR and create the branch in the `pantheon-systems` repository.

**Comment by greg-1-anderson** [comment]
I was typing the same thing as @danielbachhuber, but he beat me to it.

`Files changed 2,818` is a bit hard to review. Do you think you could make a review branch without any of the vendor changes?

A couple of minor comments on the PR.  1) Usually, the check for class-exists is wrapped around the `include` line rather than wrapping the entire contents of the class.  Any reason you did it the other way?

Why did you switch from `composer` to `curl` for installing Terminus?  The former has the advantage of being able to select the most recent version, whereas the curl replacement selects a specific version of terminus, so you won't necessarily get bugfixes over time.

**Comment by ataylorme** [comment]
> You should close this PR and create the branch in the pantheon-systems repository.

The message (below) makes it seem like it's suppressed because it's a PR, regardless of source.

> Suppressing export of environment variables TERMINUS_TOKEN fork PR builds

> Files changed 2,818 is a bit hard to review. Do you think you could make a review branch without any of the vendor changes?

Agreed - I removed the vendor directory - `composer install` can be ran during CI for tests and before deploying to WordPress.org

**Pull request closed without merging**
